// Generated by CoffeeScript 1.10.0
var findHTML, fs, optimize, parseCSS, parseHTML, run, shell;

findHTML = require('./find-html-files');

fs = require('fs');

optimize = require('./optimize');

parseCSS = require('./parse-css-refs');

parseHTML = require('./parse-html');

shell = require('shelljs');

module.exports = run = function(outputPath, cdnPrefix, htmlDirectory, assetsPath) {
  var html, htmlRefs, results, styleRefs;
  html = findHTML(htmlDirectory);
  htmlRefs = parseHTML(assetsPath, html);
  styleRefs = parseCSS(assetsPath, htmlRefs);
  shell.mkdir('-p', outputPath);
  shell.rm(outputPath + "/*");
  return results = optimize(outputPath, assetsPath, htmlRefs, styleRefs, cdnPrefix);
};
